/** @type {import('tailwindcss').Config} */

module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,svelte,ts,tsx,vue}'],
	safelist: [
		{
			pattern: /bg-(orange|green|purple|black|neutral|random)-(50|100|200|300|400|500|600|700|800|900)/,
		},
		{ pattern: /cards-(.*)/ },
		{ pattern: /bg-(sustainability|open_source|interdisciplinarity|crypto|cybersecurity)/ },
		'bg-white',
		'bg-primary',
		'bg-accent',
		'bg-saccent',
		'bg-taccent',
		'bg-baccent',
	],
	theme: {
		extend: {
			colors: {
				green: {
					50: 'var(--green-50)',
					100: 'var(--green-100)',
					200: 'var(--green-200)',
					300: 'var(--green-300)',
					400: 'var(--green-400)',
					500: 'var(--green-500)',
					600: 'var(--green-600)',
					700: 'var(--green-700)',
					800: 'var(--green-800)',
					900: 'var(--green-900)',
				},
				orange: {
					50: 'var(--orange-50)',
					100: 'var(--orange-100)',
					200: 'var(--orange-200)',
					300: 'var(--orange-300)',
					400: 'var(--orange-400)',
					500: 'var(--orange-500)',
					600: 'var(--orange-600)',
					700: 'var(--orange-700)',
					800: 'var(--orange-800)',
					900: 'var(--orange-900)',
				},
				purple: {
					50: 'var(--purple-50)',
					100: 'var(--purple-100)',
					200: 'var(--purple-200)',
					300: 'var(--purple-300)',
					400: 'var(--purple-400)',
					500: 'var(--purple-500)',
					600: 'var(--purple-600)',
					700: 'var(--purple-700)',
					800: 'var(--purple-800)',
					900: 'var(--purple-900)',
				},
				black: {
					50: 'var(--black-50)',
					100: 'var(--black-100)',
					200: 'var(--black-200)',
					300: 'var(--black-300)',
					400: 'var(--black-400)',
					500: 'var(--black-500)',
					600: 'var(--black-600)',
					700: 'var(--black-700)',
					800: 'var(--black-800)',
					900: 'var(--black-900)',
					950: 'var(--black-950)',
				},
				neutral: {
					50: 'var(--neutral-50)',
					100: 'var(--neutral-100)',
					200: 'var(--neutral-200)',
					300: 'var(--neutral-300)',
					400: 'var(--neutral-400)',
					500: 'var(--neutral-500)',
					600: 'var(--neutral-600)',
					700: 'var(--neutral-700)',
					800: 'var(--neutral-800)',
					900: 'var(--neutral-900)',
					950: 'var(--neutral-950)',
				},
				random: {
					50: 'var(--accent-50)',
					100: 'var(--accent-100)',
					200: 'var(--accent-200)',
					300: 'var(--accent-300)',
					400: 'var(--accent-400)',
					500: 'var(--accent-500)',
					600: 'var(--accent-600)',
					700: 'var(--accnet-700)',
					800: 'var(--accent-800)',
					900: 'var(--accent-900)',
				},

				// primary: pallete('primary'),
				accent: 'var(--accent-color)',
				taccent: 'var(--text-accent-color)',
				background: 'var(--bg-color)',
				saccent: 'var(--secondary-accent-color)',
				baccent: 'var(--bg-accent-color)',
				sustainability: '#69C9BF',
				open_source: '#D77733',
				interdisciplinarity: '#fff',
				crypto: '#000000',
				ecurity: '#8980f5',
				// primary: {
				// 	DEFAULT: '#F4CC9C' #FFEEDD,
				// 	light: '#FEFBF6',
				// 	800: '#F6D6B0',
				// 	600: '#F8E0C4',
				// 	400: '#FBEBD7',
				// 	200: '#FDF5EB',
				// 	100: '#FEFAF5',
				// 	50: '#FEFCFA',
				// },
			},
			fontFamily: {
				'text-desktop-base': 'var(--text-desktop-base-font-family)',
				'text-desktop-base-highlight': 'var(--text-desktop-base-highlight-font-family)',
				'text-desktop-large': 'var(--text-desktop-large-font-family)',
				'text-desktop-medium': 'var(--text-desktop-medium-font-family)',
				'text-mobile-base': 'var(--text-mobile-base-font-family)',
				'text-mobile-base-highlight': 'var(--text-mobile-base-highlight-font-family)',
				'text-mobile-large': 'var(--text-mobile-large-font-family)',
				'text-mobile-medium': 'var(--text-mobile-medium-font-family)',
				display: ['Syne', 'sans'],
				sans: ['Basis Grotesque Arabic Pro', 'sans-serif', 'sans'],
				mono: ['JetBrains Mono', 'monospace'],
			},
			boxShadow: {
				'cards-focused-green': 'var(--cards-focused-green)',
				'cards-focused-orange': 'var(--cards-focused-orange)',
				'cards-focused-purple': 'var(--cards-focused-purple)',
				'cards-simple-green': 'var(--cards-simple-green)',
				'cards-simple-orange': 'var(--cards-simple-orange)',
				'cards-simple-purple': 'var(--cards-simple-purple)',
				simple: 'var(--simple)',
			},
			fontWeight: {
				highlight: 700,
			},
			fontSize: {
				base: '18px',
				lg: '20px',
				xl: ['22px', '130%'],
				'2xl': ['', '130%'],

				mega: [
					'7.65rem',
					{
						lineHeight: '13.625rem',
					},
				],
			},
			// letterSpacing: {
			// 	normal: '-0.2rem',
			// },
			typography: {
				DEFAULT: {
					css: {
						em: { fontFamily: 'Syne', fontStyle: 'italic' },
					},
				},
			},
			borderRadius: {
				'3xl': '60px',
				'4xl': '120px',
			},
		},
	},
	plugins: [require('@tailwindcss/typography')],
	darkMode: 'class',
};
