name: Github Pages Astro CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v2
        with:
          package-manager: npm@latest
          node-version: 22

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 📢 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
